### PR TITLE
Extension helper

### PR DESCRIPTION
**Pull request by Araneidae**
Add `ExtensionHelper` class and example extension [interval.py](https://github.com/PandABlocks/PandABlocks-server/blob/extension-helper/python/test_extension/interval.py), as discussed in https://github.com/PandABlocks/PandABlocks-FPGA/issues/51.

### CODE REVIEW

**Review by thomascobb — COMMENTED** [review]
Looks reasonable, does it help with implementing something like:
https://github.com/PandABlocks/PandABlocks-FPGA/blob/master/modules/fmc_acq427/extensions/fmc_acq427.py

**Comment by Araneidae** [comment]
Interesting question.  I'd start by turning the `BitReader` and `BitsWriter` into local functions (taking advantage of getting rid of the intermediate `.read` and `.write` methods):
```python
class Extension:
    def __init__(self, count):
        pass

    def parse_read(self, request):
        offset = lookup_bit_map[request]
        return lambda _: gpio_helper.read_bit(*offset)

    def parse_write(self, request):
        offset = lookup_bit_map[request]
        return lambda _, value: gpio_helper.write_bits(value, *offset)
```
I suspect that's as clean as this one gets, as you'd otherwise have to create `get_` and `set_` methods for all the keys in `lookup_bit_map`, don't really see the point.

So no, `ExtensionHelper` doesn't do anything for you here, but the first change does.

**Comment by Araneidae** [comment]
You could also make `GPIO_Helper` the `Extension` class itself, then you wouldn't need to instantiate `gpio_helper` and the `parse_read` and `parse_write` methods would call `self.read_bit` and `self.write_bits`.  Think that would be pretty clean, in the end.

**Comment by Araneidae** [comment]
I'm going to merge this

**Pull request merged**
